version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
            key: dependency-cache-{{ checksum "package.json" }}
      - run:
            name: install-dependencies
            command: npm install
      - save_cache:
            key: dependency-cache-{{ checksum "package.json" }}
            paths:
                - ./node_modules
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: test
          command: npm run test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
